
include: package:pedantic/analysis_options.yaml

linter:
  # producing the lint.
  rules:
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_null_checks_in_equality_operators
    - camel_case_extensions
    - omit_local_variable_types
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_final_fields
    - prefer_for_elements_to_map_fromIterable
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_single_quotes
    - prefer_spread_collections

analyzer:
  exclude:
    - lib/state/*.freezed.dart
    - lib/state/*.g.dart

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
